baseURL = 'https://p-stefanski.github.io/michalbugalski_com/'
locale = 'pl-pl'
title = 'Moja strona'
theme = "hugo-book"

[params]
  BookSection = "docs"       # folder z treścią w sidebar
  BookToC = true             # spis treści w artykule
  BookSearch = true          # wyszukiwarka w sidebarze
